export const ignorePatterns: string[] = [
  '**/.aidlc/**',
  '**/.claude/**',
  '**/.clinerules/**',
  '**/.github/**',
  '**/.kiro/**',
  '**/.vendor/**',
  '**/*.toml',
  '**/*.yaml',
  '**/*.yml',
  '**/coverage/**',
  '**/dist/**',
  '**/results/compatibility/**',
  '**/node_modules/**',
  '**/target/**',
  'AGENTS.md',
  'aidlc/**',
];
